language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install --use-mirrors nose coverage coveralls"
  - "pip install --use-mirrors --editable ."
script: 
  nosetests -s --with-coverage --cover-package requirements_detector --cover-inclusive
after_success:
  coveralls
