language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --use-mirrors nose coverage coveralls"
  - "pip install --use-mirrors --editable ."
script: 
  nosetests -s --with-coverage
after_success:
  coveralls
